#@ load("@ytt:data", "data")

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: grafana
  namespace: loki
spec:
  commonName: #@ data.values.grafana_common_name
  dnsNames:
  - #@ data.values.grafana_common_name
  issuerRef:
    kind: ClusterIssuer
    name: mkcert
  secretName: loki-grafana-tls