apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  helmVersion: v3
  targetNamespace: loki
  releaseName: loki
  wait: true
  chart:
    repository: https://grafana.github.io/loki/charts
    name: loki-stack
    version: "0.40.1"
  values:
    grafana:
      enabled: true
    prometheus:
      enabled: false
    loki:
      persistence:
        enabled: true