apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail
  namespace: promtail
data:
  promtail.yaml: |
    scrape_configs:
      - job_name: pods
        scheme: http
        metrics_path: /metrics
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
            - pks-system
          selectors:
          - role: "pod"
            label: "name=vrops-cadvisor"