apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: disable-mtls
  namespace: sockshop
spec:
  host: "*.sockshop.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE