apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: node-exporter
        scheme: http
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - node-exporter
        