apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: node-exporter
        static_configs:
          - targets: ['10.0.4.3:9100','10.0.4.4:9100','10.0.4.5:9100','10.0.4.7:9100','10.0.4.8:9100','10.0.4.9:9100']