apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ['10.0.4.3:9100','10.0.4.4:9100','10.0.4.5:9100','10.0.4.7:9100','10.0.4.8:9100','10.0.4.9:9100']
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      volumes:
        - name: prometheus-volume
          configMap:
            name: prometheus
      containers:
        - name: prometheus
          image: index.docker.io/prom/prometheus:v2.18.1
          command: ['prometheus']
          args: ["--config.file", "/tmp/prometheus.yml"]
          volumeMounts:
            - name: prometheus-volume
              mountPath: /tmp/prometheus.yml
              subPath: prometheus.yml
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
