apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  helmVersion: v3
  targetNamespace: ingress-nginx
  releaseName: ingress-nginx
  wait: true
  test:
    enable: true
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: "2.11.1"
  values:
    controller:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      kind: DaemonSet
      service:
        type: ClusterIP