apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf
  namespace: telegraf
data:
  telegraf.conf: |
    [agent]
      hostname = "$HOSTNAME"
    [[inputs.kubernetes]]
      url = "https://localhost:10250/metrics/cadvisor"
      bearer_token = "/run/secrets/kubernetes.io/serviceaccount/token"
      insecure_skip_verify = true
    

    [[outputs.prometheus_client]]
      listen = ":9273"  