#@ load("@ytt:data", "data")

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: loki
  namespace: loki
spec:
  commonName: #@ data.values.hostname
  dnsNames:
  - #@ data.values.hostname
  issuerRef:
    kind: ClusterIssuer
    name: mkcert
  secretName: loki-tls