apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: vault-test
  namespace: kes
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: kes
  data:
  - name: password
    key: test-path
    property: password