apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: node-exporter-pods
        scheme: http
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - node-exporter
      - job_name: cadvisor-pods
        scheme: http
        metrics_path: /metrics
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
            - pks-system
          selectors:
          - role: "pod"
            label: "name=vrops-cadvisor"
        
    
        