#@ load("@ytt:data", "data")

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: sys-domain-cert
  namespace: istio-system
spec:
  commonName: #@ "*.sys.tas." + data.values.primary_domain
  dnsNames:
  - #@ "sys.tas." + data.values.primary_domain
  - #@ "*.sys.tas." + data.values.primary_domain
  issuerRef:
    kind: ClusterIssuer
    name: mkcert
  secretName: sys-domain-cert
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: apps-domain-cert
  namespace: istio-system
spec:
  commonName: #@ "*.apps.sys.tas." + data.values.primary_domain
  dnsNames:
  - #@ "apps.sys.tas." + data.values.primary_domain
  - #@ "*.apps.sys.tas." + data.values.primary_domain
  issuerRef:
    kind: ClusterIssuer
    name: mkcert
  secretName: apps-domain-cert