apiVersion: v1
kind: Namespace
metadata:
  name: postgres-dbs
---
apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: ccdb
  namespace: postgres-dbs
spec:
  memory: "800Mi"
  cpu: "0.5"
  storageClassName: vsphere
  serviceType: ClusterIP
  storageSize: 300M
  pgConfig:
    dbname: cloud_controller
    username: cloud_controller
---
apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: uaadb
  namespace: postgres-dbs
spec:
  memory: "800Mi"
  cpu: "0.5"
  storageClassName: vsphere
  serviceType: ClusterIP
  storageSize: 300M
  pgConfig:
    dbname: uaa
    username: uaa
---
apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: usagedb
  namespace: postgres-dbs
spec:
  memory: "800Mi"
  cpu: "0.5"
  storageClassName: vsphere
  serviceType: ClusterIP
  storageSize: 300M
  pgConfig:
    dbname: usage_service
    username: usage_service