#@ load("@ytt:data", "data")

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: concourse
  namespace: concourse
spec:
  commonName: #@ data.values.concourse_hostname
  dnsNames:
  - #@ data.values.concourse_hostname
  issuerRef:
    kind: ClusterIssuer
    name: mkcert
  secretName: concourse-web-tls