apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
  namespace: postgres
data:
  POSTGRES_DB: tas3
  POSTGRES_USER: tas3
  POSTGRES_PASSWORD: tas3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: index.docker.io/postgres:12.3
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
