#@ load("@ytt:data", "data")

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: harbor-notary
  namespace: harbor
spec:
  commonName: #@ data.values.notary_cn
  dnsNames:
  - #@ data.values.notary_cn
  issuerRef:
    kind: ClusterIssuer
    name: mkcert
  secretName: harbor-notary