#@ load("@ytt:data", "data")

apiVersion: v1
kind: Namespace
metadata:
  name: harbor
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  helmVersion: v3
  targetNamespace: harbor
  releaseName: harbor
  wait: true
  chart:
    repository: https://helm.goharbor.io
    name: harbor
    version: "1.5.0"
  values:
    clair:
      enabled: false
    chartmuseum:
      enabled: false
    trivy:
      enabled: true
    notary:
      enabled: true
    expose:
      type: ingress
      tls:
        enabled: true
        certSource: secret
        secret:
          secretName: harbor
          notarySecretName: harbor-notary
      ingress:
        hosts:
          core: #@ data.values.harbor_cn
          notary: #@ data.values.notary_cn
    externalURL: #@ "https://" + data.values.harbor_cn
    persistence:
      resourcePolicy: "keep"
      persistentVolumeClaim:
        registry:
          size: 100Gi