#@ load("@ytt:data", "data")
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vault
  namespace: vault
spec:
  rules:
  - host: #@ data.values.ingress_hostname
    http:
      paths:
      - backend:
          serviceName: vault
          servicePort: 8200
        path: /
  tls:
  - hosts:
    - #@ data.values.ingress_hostname
    secretName: vault-tls