resources:
- name: sockshop-front-end
  type: git
  source:
    uri: https://github.com/techgnosis/front-end.git
    branch: demo
- name: tanzu-gitops
  type: git
  source:
    uri: https://github.com/techgnosis/tanzu-gitops.git
    branch: master
    paths:
     - "concourse/tasks/**"
- name: sockshop-front-end-image
  type: docker-image
  source:
    repository: ((harbordomain))/library/sockshop-front-end
    tag: latest
    ca_certs:
    - domain: ((harbordomain))
      cert: |
        ((tanzu-gitops.ca_cert))
- name: concourse-helper
  type: docker-image
  source:
    repository: ((harbordomain))/library/concourse-helper
    tag: 1
    ca_certs:
    - domain: ((harbordomain))
      cert: |
        ((tanzu-gitops.ca_cert))

  


jobs:
- name: Build with TBS
  public: true
  serial: true
  plan:
  - get: sockshop-front-end
    trigger: true
  - get: concourse-helper
  - get: tanzu-gitops
  - task: handoff to TBS
    image: concourse-helper
    file: tanzu-gitops/concourse/tasks/build-image/build-image.yml
    input_mapping:
      source-code: sockshop-front-end
    params:
      tkgicluster: cluster1
      tkgiapi: ((tanzu-gitops.tkgi_url))
      tkgiuser: ((tanzu-gitops.tkgi_user))
      tkgipassword: ((tanzu-gitops.tkgi_password))
      image: sockshop-front-end



- name: Deploy to cluster
  public: true
  serial: true
  plan:
    - get: sockshop-front-end-image
      trigger: true
    - get: tanzu-gitops
    - get: concourse-helper
    - task: handoff to Kubernetes
      file: tanzu-gitops/concourse/tasks/deploy-sockshop-front-end-image/deploy-sockshop-front-end-image.yml
      image: concourse-helper
      params:
        tkgicluster: cluster1
        tkgiapi: ((tanzu-gitops.tkgi_url))
        tkgiuser: ((tanzu-gitops.tkgi_user))
        tkgipassword: ((tanzu-gitops.tkgi_password))
        harbordomain: ((harbordomain))


