resources:
- name: sockshop-carts
  type: git
  source:
    uri: https://github.com/microservices-demo/carts.git
    branch: master
- name: tanzu-gitops
  type: git
  source:
    uri: https://github.com/techgnosis/tanzu-gitops.git
    branch: master
    paths:
     - "concourse/tasks/**"
- name: sockshop-carts-image
  type: docker-image
  source:
    repository: ((harbordomain))/library/sockshop-carts
    tag: latest
    ca_certs:
    - domain: ((harbordomain))
      cert: |
        ((tanzu-gitops.ca_cert))
- name: concourse-helper
  type: docker-image
  source:
    repository: ((harbordomain))/library/concourse-helper
    tag: 1
    ca_certs:
    - domain: ((harbordomain))
      cert: |
        ((tanzu-gitops.ca_cert))

  


jobs:
- name: Build with TBS
  public: true
  serial: true
  plan:
  - get: sockshop-carts
    trigger: true
  - get: concourse-helper
  - get: tanzu-gitops
  - task: handoff to TBS
    image: concourse-helper
    file: tanzu-gitops/concourse/tasks/build-image/build-image.yml
    input_mapping:
      source-code: sockshop-carts
    params:
      tkgicluster: cluster1
      tkgiapi: ((tanzu-gitops.tkgi_url))
      tkgiuser: ((tanzu-gitops.tkgi_user))
      tkgipassword: ((tanzu-gitops.tkgi_password))
      image: sockshop-carts



- name: Deploy to cluster
  public: true
  serial: true
  plan:
    - get: sockshop-carts-image
      trigger: true
    - get: tanzu-gitops
    - get: concourse-helper
    - task: handoff to Kubernetes
      file: tanzu-gitops/concourse/tasks/deploy-image/deploy-image.yml
      image: concourse-helper
      input_mapping:
        image: sockshop-carts-image
      params:
        tkgicluster: cluster1
        tkgiapi: ((tanzu-gitops.tkgi_url))
        tkgiuser: ((tanzu-gitops.tkgi_user))
        tkgipassword: ((tanzu-gitops.tkgi_password))
        harbordomain: ((harbordomain))
        namespace: sockshop
        deployment: carts
        container: carts
        image: sockshop-carts



